### ISSUE TITLE
Can the Table of Contents be made always visible in the sidebar?

### ISSUE THREAD

**Issue by FunkyLoveCow** [talha131/pelican-elegant#142]
On long articles, the table of contents quickly scrolls out of view. Is there a way to make the table of contents always visible in the sidebar?

**Comment by cerebrux** [comment]
I tested it and it is easy to be added in the elegant.css file. You just need to add : `position: fixed;` in elegant.css file at the .table-of-content statment like this

```
.table-of-content .toc {
    position:fixed;
    font-size: .9em;
}
```

But I dought you would want to keep it because it brakes mobile version of the site. The TOC is always visible floating over the text.

**Comment by ShaunaGordon** [comment]
The breaking mobile version can be fixed by wrapping the position change in a media query, so it only does it on screens wider than a given width.
